name: multi-job
on: 
 push:
  branches: ["master"]
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - name: Get-Code
     uses: actions/checkout@v3
 test:
  needs: lint
  runs-on: ubuntu-latest
  steps:
   - name: Install Dependencies
     uses: actions/setup-node@v3
 Deploy:
  needs: test
  runs-on: ubuntu-latest
  steps: 
   - name: Deploy
     run: echo "Deploying..."
