name: multi-job
on: push
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - name: Get-Code
     uses: actions/checkout@v3
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Install Dependencies
     uses: setup-node@v3
 Deploy:
  runs-on: ubuntu-latest
  steps: 
   - name: Deploy
     run: echo "Deploying..."
